name: VCPKG CI
on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'ci-tests/**'
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Linux dependencies
        run: |
          sudo apt update -y
          sudo apt install -y autoconf autoconf-archive automake libtool libgl1-mesa-dev libglu1-mesa-dev libltdl-dev libxext-dev libwayland-dev libwayland-egl-backend-dev

      - uses: lukka/get-cmake@latest

      - name: Restore from cache and setup vcpkg executable and data files.
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Run CMake+vcpkg to build packages.
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          configurePresetAdditionalArgs: "['-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DOPENBLACK_WARNINGS_AS_ERRORS=ON']"

      - name: Upload logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vcpkg-build-logs
          path: vcpkg/buildtrees/*/*.log

      - name: Run CMake+Ninja+CTest to build/test the code (Release).
        uses: lukka/run-cmake@v10
        with:
          buildPreset: 'ninja-multi-vcpkg-release'
          testPreset: 'ninja-multi-vcpkg-release'

      - name: Upload compiled openblack
        uses: actions/upload-artifact@v4
        with:
          name: openblack-ubuntu-24.04-master
          path: cmake-build-presets/ninja-multi-vcpkg/bin
          if-no-files-found: error
